AWSTemplateFormatVersion: '2010-09-09'
Description: Simple lambda
Globals:
  Function:
    Runtime: nodejs8.10
Outputs:
  HelloProdEndpoint:
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/yo
Resources:
  Hello:
    Properties:
      CodeUri: s3://sampack-97068/362c44a7bddefef45a2a0267a7ebbfc8
      Events:
        GetEvent:
          Properties:
            Method: get
            Path: /yo
          Type: Api
      Handler: mylambda.handler
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
